version: '3.7'

services:
  
  nginx:
    image: nginx:stable-alpine
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../Auth4Web/dist/Auth4Web:/var/www/wwwroot
      - ./nginx/tls:/etc/tls
    network_mode: "host"

  api:
    hostname: api
    container_name: api
    build:
      context: ../Auth4.WebApi/
      dockerfile: Auth4-WebApi.Dockerfile
    network_mode: "host"
    volumes:
      - .settings/WebApi.settings.json:/app/WebApi.settings.json

#  auth:
#    hostname: auth
#    container_name: auth
#    build:
#      context: ../Auth4.AuthDev/
#      dockerfile: Auth4-AuthDev.Dockerfile
#    network_mode: "host"
#    volumes:
#      - .settings/AuthDev.settings.json:/app/AuthDev.settings.json
    
  auth:
    hostname: auth
    container_name: auth
    build:
      context: ../Auth4.AuthAzure/
      dockerfile: Auth4-AuthAzure.Dockerfile
    network_mode: "host"
    volumes:
      - .settings/AuthAzure.settings.json:/app/AuthAzure.settings.json

  redis:
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
 
